on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Global Protect
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect
        uses: "./"
        env:
          USER: ${{ secrets.GB_USER }}
          PASS: ${{ secrets.GB_PASSWORD }}
          SERVER: ${{ secrets.GB_SERVER }}
          PORT: ${{ secrets.GB_PORT }}
          TEST_SERVER: ${{ secrets.TEST_SERVER }}
